# Generated by Django 5.2.13 on 2026-04-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentlog',
            name='environment',
            field=models.CharField(choices=[('qa', 'QA'), ('prod_test', 'Production Testing'), ('production', 'Production')], default='qa', max_length=20),
        ),
        migrations.AddField(
            model_name='deploymentlog',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('successful', 'Successful'), ('failed', 'Failed')], default='started', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='environment',
            field=models.CharField(choices=[('dev', 'Development'), ('qa', 'QA'), ('prod_test', 'Production Testing'), ('production', 'Production')], default='dev', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('support', 'Support')], default='bug', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('qa_ready', 'QA Ready'), ('validated', 'Validated'), ('released', 'Released'), ('blocked', 'Blocked')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='qanote',
            name='result',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('blocked', 'Blocked')], default='blocked', max_length=20),
        ),
        migrations.AddField(
            model_name='release',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('qa_testing', 'QA Testing'), ('prod_test', 'Production Testing'), ('deployed', 'Deployed'), ('rollback_needed', 'Rollback Needed')], default='planned', max_length=20),
        ),
    ]
